### ISSUE TITLE
Feature Request: Mutating the dynamic data

### ISSUE THREAD

**Issue by albert-kam** [alexheretic/dynamics#3]
Great library ! I wish i encountered this sooner to avoid all the headaches with splitting and loops.

I notice the current impl is to fetch and convert and dealing with possibly non existing path of map data.

Hence a feature request mutation capability for this library.
Two things quickly come to mind:
1. Adding a node by path
2. Removing a node by path

Anyway, thank you for providing this helpful library !

**Comment by alexheretic** [comment]
It's true the library is lacking any mutation facility itself. I've tackled this in the past with something like this:

```java
Dynamic data = ...
data.dget("some.complex.path.to.inner.map").asMap().put("newData", 123);
```
This works well, but only really when you know the full path (to 'map' in the example) is present, or if you just want to ignore it if not present:
```java
data.dget("some.complex.path.to.inner.map")
    .maybe().asMap()
    .ifPresent(m -> m.put("newData", 123));
```
Does that satisfy what you had in mind?

**Comment by albert-kam** [comment]
Absolutely ! I just found out about this library yesterday, i didnt notice about asMap(). Thanks !

**Comment by alexheretic** [comment]
Great, glad that helps!
