### ISSUE TITLE
Support for getting boolean value

### ISSUE THREAD

**Issue by albert-kam** [alexheretic/dynamics#4]
Hi ! 

Is there any existing way to get boolean value without resorting to casting like this ?

`Boolean b = (Boolean) dyna.dget("status.active").asObject();`

Thank you !

**Comment by alexheretic** [comment]
Method `Dynamic#as(Class)` allows fluent casting
```java
Boolean active = dyna.dget("status.active").as(Boolean.class);
```

**Comment by albert-kam** [comment]
How could i missed that ? Thank you so much.

**Comment by alexheretic** [comment]
Np, I'm glad the lib is still useful for you!
