### ISSUE TITLE
Add the Visitor Pattern

### ISSUE THREAD

**Issue by cmoine** [alexheretic/dynamics#5]
Hi,

It is a very nice job first of all, and cannot find any equivalent so far.

However, would it be possible to add the visitor pattern out of the box to the library please ?

I would be glad to provide a Pull Request for that.

Cheers.

**Comment by alexheretic** [comment]
The lib is designed for functional/direct style in general. Cool you give me an example of the syntax you'd like and usage scenario to help me understand what your after?

**Comment by alexheretic** [comment]
To expand a `Dynamic` instance can handle nested structures containing any type and allows iterating over all of them. As such a 'visitor' can easily be implemented on-top of a dynamic, whereas static structures generally don't provide deep iteration.

```java
// Some nested data
Dynamic data = Dynamic.from(new Fluent.HashMap<>()
    .append("a", 123)
    .append("nested", new Fluent.HashMap<>()
        .append("b", "hello")
        .append("c", new BigDecimal("1230000000000.234234234"))));


data.allChildren()
    .forEach(child -> {
        if (child.is(Integer.class)) {
            System.out.printf("visit int %d%n", child.as(Integer.class));
        }
        else if (child.isString()) {
            System.out.printf("visit string '%s'%n", child.asString());
        }
        else if (child.is(BigDecimal.class)) {
            System.out.printf("visit decimal %s%n", child.as(BigDecimal.class));
        }
    });
// stdout:
//   visit int 123
//   visit string 'hello'
//   visit decimal 1230000000000.234234234
```
In this way `Dynamic` doesn't need to provide a special _Visitor_ class.

I'll close this, but please comment / re-open if I've misunderstood what you're looking for.

**Comment by cmoine** [comment]
Hi,

Indeed that's interesting, I didn't have time to see those usage. However the forEach is not recursive compared to the Visitor pattern.

I still think it could be interesting, but I agree it may not suit to the library 'phylosophy'.

What do you think ?

**Comment by alexheretic** [comment]
`Dynamic#allChildren()` returns a recursive depth-first stream of all children at any depth. Also see `Dynamic#allChildrenBreadthFirst()`.

So in the example the `.forEach` function visits each item in the nested structure regardless of depth. 

Note though that this only works for general structures ie `Collection` & `Map`s, this is because the lib is designed to work on dynamic data. So it won't be able to work out how to get to the children of some custom class.

**Comment by cmoine** [comment]
Ah ok, I didn't know allChildren was recursive, then perfect, thanks !
